name: Bug Report
description: Report a bug or issue
labels: ["bug"]
body:
  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      description: |
        Knowing how you installed the tool helps diagnose issues faster.
      options:
        - Select one
        - PyPI (pip)
        - Docker
        - Installed from source
        - Other (specify below)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Run `toolname --version` and provide the output.
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        Clearly describe the issue with details:
        - What were you trying to do?
        - What did you expect to happen?
        - What actually happened?
      placeholder: |
        Example:
        - Tried to run {command}, expected {expected outcome}, but got {actual result}.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to replicate the bug.
      placeholder: |
        1. Run this command
        2. Observe this issue
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Additional Information
      description: Any other details, logs, or screenshots?
    validations:
      required: false
  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the project's Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true